### ISSUE TITLE
Frame data has incorrect size (is larger)

### ISSUE THREAD

**Issue by melchor629** [hasenbanck/matroska-demuxer#1]
Hi! I'm having fun with MKVs, using your crate to demux some of them and extract data. But I noticed that, for a subtitle track from a MKV that is 120MB, it used like 1GB of RAM (which is insane).

So decided to take a look on the first block of the subtitle he crate read and inspect the binary:
![Slice of binary output](https://user-images.githubusercontent.com/1056963/174434625-74c6bc46-e94d-445c-9b1d-59d339705a80.png)

In the above screenshot, I selected the contents of the block, the rest is useless data (probably data from other read frames for what I can see). The file size is `484786` bytes, which is reaaaaally huge for a frame of subtitles.

Then, I decided to take a look into your code and I found this piece of code:
https://github.com/hasenbanck/matroska-demuxer/blob/e137a084f0eac7acc0d2fc092e53181c88246606/src/lib.rs#L1564

I decided to modify your code a bit with this steps:

- Added a new field in `Frame` with the size: `pub size: usize` https://github.com/hasenbanck/matroska-demuxer/blob/e137a084f0eac7acc0d2fc092e53181c88246606/src/lib.rs#L65
- Added a new line after this `frame.size = size;` https://github.com/hasenbanck/matroska-demuxer/blob/e137a084f0eac7acc0d2fc092e53181c88246606/src/lib.rs#L1573

And tried the same code I have but using a slice of data: `&frame.data[0..frame.size]`, and now I have the following binary output:
![Another slice of binary output](https://user-images.githubusercontent.com/1056963/174435024-1d8a971f-8de4-4fbc-8a97-ab384df3f008.png)

I think my solution is just a fast workaround to get things done, but ultimately I would like to have a proper way to grab the right data from it. I hope my issue and investigation helps a bit :)

Thanks for the crate!

**Comment by hasenbanck** [comment]
Could you test the PR I uploaded?

**Comment by melchor629** [comment]
Hi, with the PR it seems to work fine. Thanks!
