### ISSUE TITLE
CodecPrivate (at least in subtitles) contains the whole TrackEntry and more

### ISSUE THREAD

**Issue by melchor629** [hasenbanck/matroska-demuxer#2]
Hi again!

As per spec, the SSA/ASS subtitles have the initial section of the file in the `CodecPrivate` section of the `TrackEntry`. So I tried to read the section using `track.codec_private()` and what I've got is the whole `TrackEntry` in the data.

Initial part of the data I got from the method:
![CodecPrivate from library](https://user-images.githubusercontent.com/1056963/174435767-a8ac05ac-f5fe-4186-97e0-aa5da90bdd63.png)

And here, the `TrackEntry` itself from the mkv directly (with parsed fields and selected data is the contents of the `CodecPrivate` itself).
![CodecPrivate from the mkv itself, parsed](https://user-images.githubusercontent.com/1056963/174435778-c59013a8-7e4d-4656-98c5-abdf2add36b2.png)

This time, I did not investigated much to find what happens, just I found out that the below line is where it reads the binary contents and the offset just points to the whole `TrackEntry`, and the size is larger that what it should (it reads part of the following data in the mkv).
https://github.com/hasenbanck/matroska-demuxer/blob/e137a084f0eac7acc0d2fc092e53181c88246606/src/lib.rs#L306

One more time, hope it helps fix this small issue :)

Thanks!!

**Comment by hasenbanck** [comment]
Please test the attached PR.

**Comment by melchor629** [comment]
Hi again! Tested the PR and it is reading the codec private section properly. Thanks for the quick PRs!! :)

**Comment by hasenbanck** [comment]
I think I never really tested subtitles. So extra small test files or test cases are always welcome.

**Comment by hasenbanck** [comment]
I pushed a new version to creates.
